import { describe, expect, it } from "vitest";
import { MARKER_TRACKS_BY_FILENAME } from "./markerTracks.js";
import { ORIGINAL_MARKER_TRACK } from "./markerTrack.js";

describe("per-video marker tracks", () => {
  it("starts empty until this production's attract clips are tracked", () => {
    // Generated by `pnpm generate-idle-marker-tracks` from the marker visible
    // in each attract clip. There is no footage in the repo yet, so the
    // registry is empty and every clip falls back to the static placement.
    expect(Object.keys(MARKER_TRACKS_BY_FILENAME)).toEqual([]);
  });

  it("falls back to a static, centred, axis-aligned square", () => {
    expect(ORIGINAL_MARKER_TRACK).toMatchObject({ width: 1920, height: 1080 });
    expect(ORIGINAL_MARKER_TRACK.frames).toHaveLength(1);

    // [top-left x/y, top-right x/y, bottom-right x/y, bottom-left x/y]
    const [tlx, tly, trx, try_, brx, bry, blx, bly] = ORIGINAL_MARKER_TRACK.frames[0]!;
    // Axis-aligned: both top corners share a y, both left corners an x, etc.
    expect(tly).toBe(try_);
    expect(bry).toBe(bly);
    expect(tlx).toBe(blx);
    expect(trx).toBe(brx);
    // Centred in the 1920x1080 frame, and square.
    expect(tlx! + trx!).toBe(1920);
    expect(tly! + bry!).toBe(1080);
    expect(trx! - tlx!).toBe(bry! - tly!);
  });
});
