// Generated by scripts/generate-idle-marker-tracks.py. Do not edit by hand.
import type { MarkerTrack } from "./markerTrack.js";

// Empty until this production's attract clips exist in apps/display/src/assets/.
// Add the clips, then run `pnpm generate-idle-marker-tracks` and commit the result.
export const GENERATED_MARKER_TRACKS: Readonly<Record<string, MarkerTrack>> = {};
